export const VConfig = {
  sizing: {
    BASE_PX: 160,

    MIN_SCREEN_PX: 10,

    MAX_SCREEN_PX: 160 * 2,

    ZOOM_FACTOR: 2,

    DEPTH_SHRINK: 0.6,

    SIBLING_VISUAL_EXP: 0.45,

    WORLD_SIBLING_EXP: 0.7,
  },

  elements: {
    DIM_OPACITY: 0.18,

    HOVER_SCALE_FACTOR: 1.15,

    HOVER_DURATION: 0.15,

    SPAWN_DURATION: 0.25,

    LABEL_SIZE_RATIO: 0.24,
    LABEL_MIN_FONT: 10,
    LABEL_MAX_FONT: 18,
    LABEL_MAX_FONT_THRESHOLD: 20,

    LABEL_WIDTH_RATIO: 1.6,

    LABEL_BELOW_OFFSET: 10,
    LABEL_FONT_FAMILY: "system-ui, sans-serif",

    STROKE_EXP: 0.4,

    CONTAINER_BG_OPACITY: 0.3,

    CHAR_WIDTH_RATIO: 0.6,
    LABEL_TARGET_WIDTH_RATIO: 0.8,
  },

  decorations: {
    RECURSIVE_COLOR: "#f97316",
    CONNECTING_COLOR: "#3b82f6",

    RECURSIVE_RING_OFFSET: 5,
    RECURSIVE_RING_DASH: [5, 4] as number[],
    RECURSIVE_RING_WIDTH: 2,

    RECURSIVE_TEXT_OFFSET: 16,
    RECURSIVE_TEXT_X_RATIO: 0.18,
    RECURSIVE_TEXT_SIZE_RATIO: 0.28,

    CONNECTING_RING_OFFSET: 8,

    CONNECTING_RING_OFFSET_RECURSIVE: 14,
    CONNECTING_RING_WIDTH: 2.5,
  },

  relationships: {
    DIM_OPACITY: 0.12,

    STROKE_WIDTH: 1.5,

    ARROW_SIZE: 8,
  },

  rendering: {
    REL_DIM_OPACITY: 0.1,
    REL_NORMAL_OPACITY: 0.75,
    REL_STROKE_WIDTH: 1.5,
    REL_DASH: [8, 6] as number[],
    REL_LABEL_FONT_SIZE: 10,
    REL_LABEL_MIN_FONT: 8,
    REL_LABEL_MAX_FONT_THRESHOLD: 14,
    REL_LABEL_OFFSET: 12,

    DECORATION_STROKE_WIDTH: 1.5,

    ANIM_TICK_RATIO: 0.8,
    ANIM_MAX_DURATION: 0.6,
  },

  shapes: {
    ARROW_INSET: 8,
    TRIANGLE_INSET: 12,
    DIAMOND_INSET: 20,
    CIRCLE_INSET: 10,
    ARROW_SIZE: 8,
    TRIANGLE_H: 12,
    TRIANGLE_W: 7,
    DIAMOND_H: 10,
    DIAMOND_W: 5,
    CIRCLE_R: 5,
  },

  elementShapes: {
    CORNER_RADIUS: 5,
    DASH_STATE: [5, 5] as number[],
    DASH_FUNCTION: [2, 2] as number[],
    DASH_FLOW: [10, 5] as number[],
    DASH_CHOICE: [2, 5, 10, 5] as number[],
  },
} as const;
